### ISSUE TITLE
Unknown option: load-plugins

### ISSUE THREAD

**Issue by benrush** [r3b/phantomjs#3]
Following installing your fork (thank you by the way) I tried your example however received the error that the option load-plugins was unknown.

I then tried installing flashplayer using

rpm -ivh http://linuxdownload.adobe.com/adobe-release/adobe-release-i386-1.0-1.noarch.rpm
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
yum check-update
yum -y install flash-plugin nspluginwrapper

but still got the same result. Can you help please?

**Comment by r3b** [comment]
The main fork of phantomjs no longer recognizes load-plugins as an option. Are you sure you were specifying the version built from my fork and not a previously installed version?

**Comment by benrush** [comment]
Hi Ryan

First thank you for getting back to me.

Yes i am sure it is yours because i had installed v 1.9.1 of the normal 
one and i then compiled yours put the binary into location and now it 
shows v 1.9

do you have any suggestgions because it would really help? We need this 
for a project so I would be happy to pay for your time. I can even send 
you the server to login to.

**Comment by JamesMGreene** [comment]
The mainline PhantomJS doesn't have a version 1.9.1 yet, so you must be mistaken on what version you had installed. I'd agree with Ryan that you need to verify your version and ensure that your `which phantomjs` is finding your compiled version instead of a pre-built binary in some other folder.

Other than that, be sure to:
1. Get the latest code as there was a [patch to the `load-plugins` option](https://github.com/r3b/phantomjs/commit/6d843e00efda567dad20754bba03d74e4a93db8e) a few days after Ryan's initial blog post. In your local repo, do a `git pull` (or `git pull upstream master`, or whatever your configuration dictates).
2. Preceding the `load-plugins` option with two dashes, i.e. `phantomjs --load-plugins=true myFlashyScript.js`.

**Comment by benrush** [comment]
Ok I built a completely fresh centos 6.3 server and did it from scratch. Still the same issue unfortunately.

git clone git://github.com/r3b/phantomjs.git

sudo git checkout 1.9

cd phantomjs/

sudo ./build.sh

cd bin/

sudo cp phantomjs /usr/local/bin

[ec2-user@ip-172-31-13-192 ~]$ phantomjs -v

1.9.0

I then made your test page and got

[ec2-user@ip-172-31-13-192 ~]$ phantomjs --load-plugins=true test.js

Error: Unknown option: load-plugins

Do I need to install X11 and run through a DISPLAY to get it to work?

Thanks for your help so far.

**Comment by JamesMGreene** [comment]
You should be building the "master" branch, not the "1.9" branch. The "1.9" branch is just inherited from the PhantomJS mainline (upstream) repo.

**Comment by benrush** [comment]
I changed to not grab the 1.9 branch and unfortunately now hit another block

qt/include/QtScript/../../src/script/api/qscriptengine.h:31: error: âQtValidLicenseForScriptModuleâ does not name a type

In file included from qt/include/QtNetwork/qnetworkaccessmanager.h:1,

```
             from qt/include/QtWebKit/../../src/3rdparty/webkit/Source/WebKit/qt/Api/qwebframe.h:29,

             from qt/include/QtWebKit/qwebframe.h:1,

             from qt/include/QtWebKit/QWebFrame:1,

             from utils.h:35,

             from phantom.cpp:44:
```

qt/include/QtNetwork/../../src/network/access/qnetworkaccessmanager.h:51: error: âQtValidLicenseForNetworkModuleâ does not name a type

In file included from qt/include/QtCore/qmutex.h:1,

```
             from qt/include/QtCore/QMutex:1,

             from webserver.h:35,

             from phantom.cpp:46:
```

qt/include/QtCore/../../src/corelib/thread/qmutex.h:53: error: âQtValidLicenseForCoreModuleâ does not name a type

In file included from qt/include/QtCore/qsemaphore.h:1,

```
             from qt/include/QtCore/QSemaphore:1,

             from webserver.h:36,

             from phantom.cpp:46:
```

qt/include/QtCore/../../src/corelib/thread/qsemaphore.h:51: error: âQtValidLicenseForCoreModuleâ does not name a type

In file included from qt/include/QtCore/qsettings.h:1,

```
             from qt/include/QtCore/QSettings:1,

             from cookiejar.h:34,

             from phantom.cpp:50:
```

qt/include/QtCore/../../src/corelib/io/qsettings.h:52: error: âQtValidLicenseForCoreModuleâ does not name a type

In file included from qt/include/QtNetwork/qnetworkcookie.h:1,

```
             from qt/include/QtNetwork/QNetworkCookie:1,

            from qt/include/QtNetwork/../../src/network/access/qnetworkcookiejar.h:49,

             from qt/include/QtNetwork/qnetworkcookiejar.h:1,

             from qt/include/QtNetwork/QNetworkCookieJar:1,

             from cookiejar.h:35,

             from phantom.cpp:50:
```

qt/include/QtNetwork/../../src/network/access/qnetworkcookie.h:54: error: âQtValidLicenseForNetworkModuleâ does not name a type

In file included from qt/include/QtNetwork/qnetworkcookiejar.h:1,

```
             from qt/include/QtNetwork/QNetworkCookieJar:1,

             from cookiejar.h:35,

             from phantom.cpp:50:
```

qt/include/QtNetwork/../../src/network/access/qnetworkcookiejar.h:55: error: âQtValidLicenseForNetworkModuleâ does not name a type

make[1]: **\* [phantom.o] Error 1

**Comment by r3b** [comment]
I've added a few additional notes and a couple of binary builds to my original blog post: http://www.ryanbridges.org/2013/05/21/putting-the-flash-back-in-phantomjs/

**Comment by benrush** [comment]
Thanks for the extra info. I am building on Centos and even though I 
found all the dependancies for that OS I got the same error. I am going 
o setup a Unbuntu server instead to use your binarries.

Thanks for the help though.

**Comment by r3b** [comment]
No problem. If you can't get it build with Ubuntu, let me know.

**Comment by benrush** [comment]
Hi Ryan

Thank you

I got it running on unbuntu but I could not get flash working.

I tried v11 and v10. The so file was placed in the plugin path for 
qtwebkit however no luck.

I even ran a strace and found it had located the so file.

I have no idea what else to try. I have a dev server setup I can send 
you access details for and I am happy to pay for your time. I think it 
is likely to be something simple but I have tried eveerything i can 
think of and spent many hours combing the web for any ideas.

Do you have a direct email I can contact you on?

**Comment by r3b** [comment]
You can email me at ryan.bridges@gmail.com

**Comment by willwh** [comment]
Hi Guys,

I know this is an old issue, but I'm trying to get this running on a current 14.04 server. We've been using slimerjs with xvfb, and I'd love to give phantom a rip and see what kind of load differences we can expect (we're using flash objects)

```
root/phantomjs/src/qt/lib/libQtWebKit.a(MediaPlayerPrivateGStreamer.o): In function `WebCore::MediaPlayerPrivateGStreamer::registerMediaEngine(void (*)(WTF::PassOwnPtr<WebCore::MediaPlayerPrivateInterface> (*)(WebCore::MediaPlayer*), void (*)(WTF::HashSet<WTF::String, WTF::StringHash, WTF::HashTraits<WTF::String> >&), WebCore::MediaPlayer::SupportsType (*)(WTF::String const&, WTF::String const&), void (*)(WTF::Vector<WTF::String, 0ul>&), void (*)(), void (*)(WTF::String const&)))':
MediaPlayerPrivateGStreamer.cpp:(.text._ZN7WebCore27MediaPlayerPrivateGStreamer19registerMediaEngineEPFvPFN3WTF10PassOwnPtrINS_27MediaPlayerPrivateInterfaceEEEPNS_11MediaPlayerEEPFvRNS1_7HashSetINS1_6StringENS1_10StringHashENS1_10HashTraitsISA_EEEEEPFNS5_12SupportsTypeERKSA_SK_EPFvRNS1_6VectorISA_Lm0EEEEPFvvEPFvSK_EE+0x90): undefined reference to `void WTF::freeOwnedGPtr<_GError>(_GError*)'
/root/phantomjs/src/qt/lib/libQtWebKit.a(MediaPlayerPrivateGStreamer.o): In function `WebCore::MediaPlayerPrivateGStreamer::isAvailable()':
MediaPlayerPrivateGStreamer.cpp:(.text._ZN7WebCore27MediaPlayerPrivateGStreamer11isAvailableEv+0x70): undefined reference to `void WTF::freeOwnedGPtr<_GError>(_GError*)'
/root/phantomjs/src/qt/lib/libQtWebKit.a(MediaPlayerPrivateGStreamer.o): In function `WebCore::MediaPlayerPrivateGStreamer::MediaPlayerPrivateGStreamer(WebCore::MediaPlayer*)':
MediaPlayerPrivateGStreamer.cpp:(.text._ZN7WebCore27MediaPlayerPrivateGStreamerC2EPNS_11MediaPlayerE+0x1a0): undefined reference to `void WTF::freeOwnedGPtr<_GError>(_GError*)'
/root/phantomjs/src/qt/lib/libQtWebKit.a(MediaPlayerPrivateGStreamer.o): In function `WebCore::MediaPlayerPrivateGStreamer::create(WebCore::MediaPlayer*)':
MediaPlayerPrivateGStreamer.cpp:(.text._ZN7WebCore27MediaPlayerPrivateGStreamer6createEPNS_11MediaPlayerE+0x1c0): undefined reference to `void WTF::freeOwnedGPtr<_GError>(_GError*)'
/root/phantomjs/src/qt/lib/libQtWebKit.a(MediaPlayerPrivateGStreamer.o): In function `WebCore::MediaPlayerPrivateGStreamer::handleMessage(_GstMessage*)':
MediaPlayerPrivateGStreamer.cpp:(.text._ZN7WebCore27MediaPlayerPrivateGStreamer13handleMessageEP11_GstMessage+0x120): undefined reference to `void WTF::freeOwnedGPtr<_GError>(_GError*)'
/root/phantomjs/src/qt/lib/libQtWebKit.a(MediaPlayerPrivateGStreamer.o):MediaPlayerPrivateGStreamer.cpp:(.text._ZN7WebCoreL33mediaPlayerPrivateMessageCallbackEP7_GstBusP11_GstMessagePNS_27MediaPlayerPrivateGStreamerE+0x120): more undefined references to `void WTF::freeOwnedGPtr<_GError>(_GError*)' follow
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/phantomjs] Error 1
make[1]: Leaving directory `/root/phantomjs/src'
make: *** [sub-src-phantomjs-pro-make_default-ordered] Error 2
```

Any ideas here? :)
