### ISSUE TITLE
Project MESSAGE: Disabling video due the lack of GLib/Gio/GStreamer.

### ISSUE THREAD

**Issue by designboxcom** [r3b/phantomjs#4]
Hello,

First of all, thank you very much for this contribution.

I am trying to compile your version of PhantomJS on a Centos 5.9 server.
However, even if the process is going through without fatal errors, I can't capture screenshots of Flash pages.
I noticed during the compilation the following error:
**Project MESSAGE: Disabling video due the lack of GLib/Gio/GStreamer.**

Of course, the necessary GStreamer Libraries are installed on the server:

```
gstreamer.i386                            0.10.20-3.el5                installed
gstreamer-devel.i386                      0.10.20-3.el5                installed
gstreamer-ffmpeg.i386                     0.10.6-1.el5.rf              installed
gstreamer-plugins-bad.i386                0.10.8-5.el5.rf              installed
gstreamer-plugins-base.i386               0.10.20-3.0.1.el5_3          installed
gstreamer-plugins-ugly.i386               0.10.11-2.el5.rf             installed
gstreamer-tools.i386                      0.10.20-3.el5                installed
```

On the top of this, I've followed the step by step provided on your blog (http://www.ryanbridges.org/2013/05/21/putting-the-flash-back-in-phantomjs/) but still no luck.
I also tried the fix provided on Nikolay Matsievsky Blog (http://blog.webogroup.com/2013/04/how-to-setup-completely-headless.html) without any further success...

Not sure now in which direction I should give a try... 
Any idea?

**Comment by r3b** [comment]
I ran into a similar issue at some point. The gstreamer libs weren't being included because I had installed the C packaged rather than the C++ packages. The C++ packages for Ubuntu are:

libgstreamermm-0.10-2 - C++ wrapper library for the multimedia library GStreamer (shared libraries)
libgstreamermm-0.10-dbg - C++ wrapper library for the multimedia library GStreamer (debug symbols)
libgstreamermm-0.10-dev - C++ wrapper library for the multimedia library GStreamer (development files)

**Comment by designboxcom** [comment]
Thank you Ryan.
Unfortunately, I wasn't able to find those libraries on the Centos repositories...

**Comment by designboxcom** [comment]
Okay, it seems these libraries are only available for Centos 6:

```
gstreamermm-0.10.7-1.el6.nux.i686.rpm
gstreamermm-devel-0.10.7-1.el6.nux.i686.rpm
gstreamermm-debuginfo-0.10.7-1.el6.nux.i686.rpm
```

:(

**Comment by r3b** [comment]
The more I think about this, the more I think it could be a red herring.  Can you give me a link to the page you are trying to capture?

**Comment by designboxcom** [comment]
Sure:
http://www.dhs.state.il.us/accessibility/tests/flash/video.html  :yum: 
And this is the screenshot returned... :(
![video](https://f.cloud.github.com/assets/2687618/814725/3d4dc75a-ef1b-11e2-9758-e6098fe1dc05.png)

**Comment by r3b** [comment]
I ask because I had a wmode issue with one of my sites that was causing the plugin frame not to be captured with the rest of the window.

Did you install the flash-installer packages for CentOS?  Someone mentioned int he comments that they had to it in a specific order on CentOS.

**Comment by designboxcom** [comment]
I guess I tried everything I was aware of... :)
Uninstalled Flash plugin, checked the version, installed it again directly from Adobe repository. (Also tried with the old version 10 as advised somewhere). 
Tried also to call Phantomjs adding before the export command:

```
export LIBXCB_ALLOW_SLOPPY_LOCK=1
```

Also tried to run the script through xvfb-run.

```
export LIBXCB_ALLOW_SLOPPY_LOCK=1;xvfb-run --server-args="-screen 0, 1024x768x24" /root/phantomjs/bin/phantomjs rasterize.js http://www.dhs.state.il.us/accessibility/tests/flash/video.html video.png
```

I also symlinked /usr/lib/flash-plugin/libflashplayer.so to /usr/lib/mozilla/plugins-wrapped/ and /usr/lib/mozilla/plugins/. I also symlinked it to /root/.mozilla/plugins/ and to /home/MYUSERNAME/.mozilla/plugins/.

I installed totem-mozplugin.i386, alsa-plugins-pulseaudio and libtheora-devel as advised somewhere. Not sure though what are they used for but I only wanted to be sure I was not missing any kind of librairies.

I also tried to force the QTWEBKIT-PLUGIN-PATH with

```
QTWEBKIT_PLUGIN_PATH=/usr/lib/browser-plugins:/usr/lib/flash-plugin:/usr/lib/mozilla/plugin:/usr/lib/mozilla/plugins:/usr/lib/opera/plugins;
```

Then, I tried to modify the Headers in my rasterize.js file as follow:

```
var page = new WebPage(),
    address, output, size;
page.onInitialized = function () {
        page.evaluate(function () {
            window.navigator = {
                plugins: {length: 2, 'Shockwave Flash': {name: 'Shockwave Flash', description: 'Shockwave Flash 11.6 r602'}},
                mimeTypes: {length: 2, "application/x-shockwave-flash":
                    {description: "Shockwave Flash", suffixes: "swf", type: "application/x-shockwave-flash", enabledPlugin: {description: "Shockwave Flash 11.6 r602"}}
                },
                appCodeName: "Mozilla",
                appName: "Netscape",
                appVersion: "5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.172 Safari/537.22",
                cookieEnabled: true,
                language: "en",
                onLine: true,
                platform: "CentOS 5.7",
                product: "Gecko",
                productSub: "20030107",
                userAgent: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.172 Safari/537.22",
            };
        });
    };
if (phantom.args.length < 2 || phantom.args.length > 3) {
    console.log('Usage: rasterize.js URL filename');
    phantom.exit();
} else {
    address = phantom.args[0];
    output = phantom.args[1];
    page.viewportSize = { width: 600, height: 600 };
    page.open(address, function (status) {
        if (status !== 'success') {
            console.log('Unable to load the address!');
        } else {
            window.setTimeout(function () {
                page.render(output);
                phantom.exit();
            }, 200);
        }
    });
}
```

Uninstalled and intalled again the Flash plugin.
Rebooted the server....

I am now out of ideas... :P

**Comment by r3b** [comment]
Let me provision a CentOS 5.9 server and see if I can get it going.

**Comment by designboxcom** [comment]
Have you found time to try it on Centos 5.9?

**Comment by designboxcom** [comment]
While still searching, I found this:
http://qt-project.org/forums/viewthread/16595

Does it help?

**Comment by r3b** [comment]
I tried it out on CentOS 5.9 and couldn't get it to compile. Let me give it another shot with the info from that thread.

**Comment by designboxcom** [comment]
Please, be my guest... :)

**Comment by r3b** [comment]
Good news: I finally got it to compile on CentOS 5.9.
Bad News: I also could not see the rendered plugin.

But it can't hide forever...

**Comment by r3b** [comment]
...or maybe it can. I gave it a good college try and got nowhere. The next logical step would be to try compiling individual dependencies by hand.  Have you tried Ubuntu? :-)

**Comment by designboxcom** [comment]
No, because Centos 5.9 is our production servers environment.
Nevermind, I guess the only solution, even if I wanted to avoid it actually, will be to upgrade the servers to Centos 6...
Thank you very much for your help Ryan.

**Comment by r3b** [comment]
Have you verified that the plugin integration works with CentOS 6?

**Comment by designboxcom** [comment]
I might have misunderstood something but I was under the impression some have been able to install it on Centos 6:
http://www.ryanbridges.org/2013/05/21/putting-the-flash-back-in-phantomjs/#comment-92

**Comment by r3b** [comment]
I'm also under that impression. But after trying to wrangle all of the dependencies on CentOS, I would test it out first to be sure :-)
