### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by AcidWeb** [r3b/phantomjs#5]
Hello,

This version should work on Windows? Because I can compile it without any problems but Flash still don't work. I need some special version of flash?

**Comment by JamesMGreene** [comment]
You may need to copy the main Flash Player DLL into a different folder or set a particular environment variable. Read more:
- http://qt-project.org/doc/qt-4.8/qtwebkit.html/#netscape-plugin-support
- http://qt-project.org/forums/viewthread/12496

**Comment by AcidWeb** [comment]
Moving 32bit NPSWF32.dll to program directory and/or setting QTWEBKIT_PLUGIN_PATH not helped.

**Comment by r3b** [comment]
I managed to compile it and try those tricks as well, with the same result.  My gut feeling is that I must have missed something wrt Windows, as I do not see phantomjs attempting to load the DLL.  The search continues...

**Comment by r3b** [comment]
I had better luck the next time. Here's a link to the working win32 version: http://fstr.co/1qaDVie
